version: '2'
services:
  proxy:
    build: ./
    container_name: proxy
    networks:
      - m1_service_front
      - m2_service_front
      - my_books_service_front
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

networks:
  m1_service_front:
    external:
      name: microservice1_front
  m2_service_front:
    external:
      name: microservice2_front
  my_books_service_front:
    external:
      name: mybooks_front

