version: '2'
services:
  app:
    build: ./
    container_name: m2_service
    # image: nginx:1.9
    # volumes:
    #   - .:/usr/share/nginx/html/
    expose:
      - "80"
    networks:
      - front

networks:
  front:
